In [ ]:
# DATA : raw_data.csv 
# GOAL : clean real-world data

# CONCEPTS:
# detecting & removing duplicates (full row + subset)
# handling missing values with ffill
# typecasting columns with astype
# safe experimentation with df.copy()
# converting date strings with pd.to_datetime

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
#Handling duplication

In [5]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [6]:
#Multiple duplicated values can create possible bias when training models

In [15]:
df[['country', "gender"]].duplicated() #checking column wise

0    False
2    False
4    False
5    False
6    False
7    False
9    False
dtype: bool

In [50]:
df2=df.copy()

In [8]:
df2.drop_duplicates(inplace=True) #modifies original data

In [51]:
df2

   id          name  age country  gender   income
0   1      John Doe   29     USA    Male  55000.0
2   2    Jane Smith   29  Canada  Female  62000.0
4   4  Maria Garcia   34   Spain  Female      NaN
5   5        Li Wei   27   China    Male  51000.0
6   6           NaN   45   India  Female  73000.0
7   7    Ahmed Khan   38     NaN    Male  68000.0
9   9   Carlos Ruiz   38  Mexico    Male  45000.0

In [36]:
df2.drop_duplicates(subset=['country'])    # drop if country repeats

In [52]:
df2

   id          name  age country  gender   income
0   1      John Doe   29     USA    Male  55000.0
2   2    Jane Smith   29  Canada  Female  62000.0
4   4  Maria Garcia   34   Spain  Female      NaN
5   5        Li Wei   27   China    Male  51000.0
6   6           NaN   45   India  Female  73000.0
7   7    Ahmed Khan   38     NaN    Male  68000.0
9   9   Carlos Ruiz   38  Mexico    Male  45000.0

In [53]:
df2['age'].ffill()

0    29
2    29
4    34
5    27
6    45
7    38
9    38
Name: age, dtype: int64

In [49]:
df2.dtypes

dtype('int64')

In [54]:
df2['age'].astype('int64') #typecasting

0    29
2    29
4    34
5    27
6    45
7    38
9    38
Name: age, dtype: int64

In [55]:
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [60]:
df2['age']

0    29
2    29
4    34
5    27
6    45
7    38
9    38
Name: age, dtype: int64

In [63]:
date_str = "2026-12-06"
date_strt = pd.to_datetime(date_str)
type(date_strt)

pandas._libs.tslibs.timestamps.Timestamp