In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

In [5]:
df.groupby('country')["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [6]:
df.groupby('country')["income"].min() #Categorization, then aggregation

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [7]:
df.groupby('gender')["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [11]:
df.groupby("country")["income"].agg(["mean","min","max"]) #getting aggregates by grouping incomes of countries

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [12]:
df.groupby("country")["income"].agg(avg="mean",min_salary="min",max_salary="max") #renaming cols

             avg  min_salary  max_salary
country
Canada   62000.0     62000.0     62000.0
China    51000.0     51000.0     51000.0
India    73000.0     73000.0     73000.0
Mexico   45000.0     45000.0     45000.0
Spain        NaN         NaN         NaN
USA      55400.0     47000.0     62000.0

In [13]:
df.groupby("country").agg({
    "age": "mean",
    "income": "mean"
})   # aggregate on multiple cols

          age   income
country
Canada    NaN  62000.0
China    27.0  51000.0
India    45.0  73000.0
Mexico    NaN  45000.0
Spain    34.0      NaN
USA      29.5  55400.0