In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

In [4]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [ ]:
'''Whenever the sum of missing values is high, it is not advisable to use that column 
for major analysis or model training'''

In [19]:
df.dropna() #empty col drop {atleast one}
df.dropna(axis=1) # empty row drop {atleast one}

df.fillna("missing") #fills  a specific thing in missing

    id          name      age  country   gender   income
0    1      John Doe     29.0      USA     Male  55000.0
1    1      John Doe     29.0      USA     Male  55000.0
2    2    Jane Smith  missing   Canada   Female  62000.0
3    3          Alex  missing      USA  Unknown  47000.0
4    4  Maria Garcia     34.0    Spain   Female  missing
5    5        Li Wei     27.0    China     Male  51000.0
6    6       missing     45.0    India   Female  73000.0
7    7    Ahmed Khan     38.0  missing     Male  68000.0
8    8    Rachel Lee     29.0      USA   Female  62000.0
9    9   Carlos Ruiz  missing   Mexico     Male  45000.0
10  10   Emily Davis     31.0      USA  missing  58000.0

In [24]:
cleaned_data = df.copy() #creating a copy of the original data and keeping the mean age in missing fields
age_mean=cleaned_data["age"].mean()
cleaned_data["age"].fillna(age_mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [27]:
cleaned_data.ffill() #uses above value in missing fields in up to down direction
cleaned_data.bfill()  #uses above value in missing fields in down to up direction

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0