In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df2=df.copy()

In [4]:
# Transformation / Feature Engineering
df2 = df.copy()

# apply a function to a row or col using lambda
df2["tax"] = df2["income"].apply(lambda x : "10%" if x < 60000 else "20%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  20%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

In [5]:
#mapping out values 
new_gender_vals = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(new_gender_vals)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  20%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [6]:
# assign some new values
df2=df2.assign(new_income = df2["income"] * 1.1)
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  20%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [7]:
# replace specific values
df2['country'] = df2["country"].replace("USA", "US")
df2['name'] = df2['name'].replace("Alex", "Alex Hales")
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3    Alex Hales   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  20%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [8]:
# Transformation - Sorting
df2 = df.copy()

# Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]
df2.rename(columns={"Name": "Initials"}, inplace=True) #for changing column label
df2.rename(index={0: "first"},inplace=True)
df2#for changing row label

       Id      Initials   Age Country   Gender   Income
first   1      John Doe  29.0     USA     Male  55000.0
1       1      John Doe  29.0     USA     Male  55000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0
3       3          Alex   NaN     USA  Unknown  47000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
5       5        Li Wei  27.0   China     Male  51000.0
6       6           NaN  45.0   India   Female  73000.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0

In [9]:
# Sorting - values & index                  # sort values in ascending
sorted_df2=df2.sort_values(["Age", "Income"])            # sorts for age, if age is same then sorts for income 
sorted_df2

       Id      Initials   Age Country   Gender   Income
5       5        Li Wei  27.0   China     Male  51000.0
first   1      John Doe  29.0     USA     Male  55000.0
1       1      John Doe  29.0     USA     Male  55000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
6       6           NaN  45.0   India   Female  73000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
3       3          Alex   NaN     USA  Unknown  47000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0

In [10]:
 # Reset Index
sorted_df2.reset_index()

    index  Id      Initials   Age Country   Gender   Income
0       5   5        Li Wei  27.0   China     Male  51000.0
1   first   1      John Doe  29.0     USA     Male  55000.0
2       1   1      John Doe  29.0     USA     Male  55000.0
3       8   8    Rachel Lee  29.0     USA   Female  62000.0
4      10  10   Emily Davis  31.0     USA      NaN  58000.0
5       4   4  Maria Garcia  34.0   Spain   Female      NaN
6       7   7    Ahmed Khan  38.0     NaN     Male  68000.0
7       6   6           NaN  45.0   India   Female  73000.0
8       9   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
9       3   3          Alex   NaN     USA  Unknown  47000.0
10      2   2    Jane Smith   NaN  Canada   Female  62000.0

In [11]:
# Ranking
df2["Ranking"] = df2["Income"].rank(ascending=False,method="dense")
df2

       Id      Initials   Age Country   Gender   Income  Ranking
first   1      John Doe  29.0     USA     Male  55000.0      5.0
1       1      John Doe  29.0     USA     Male  55000.0      5.0
2       2    Jane Smith   NaN  Canada   Female  62000.0      3.0
3       3          Alex   NaN     USA  Unknown  47000.0      7.0
4       4  Maria Garcia  34.0   Spain   Female      NaN      NaN
5       5        Li Wei  27.0   China     Male  51000.0      6.0
6       6           NaN  45.0   India   Female  73000.0      1.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8       8    Rachel Lee  29.0     USA   Female  62000.0      3.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0      8.0
10     10   Emily Davis  31.0     USA      NaN  58000.0      4.0

In [12]:

df2[["Id", "Initials", "Age", "Income", "Gender", "Country", "Ranking"]]
df2

       Id      Initials   Age Country   Gender   Income  Ranking
first   1      John Doe  29.0     USA     Male  55000.0      5.0
1       1      John Doe  29.0     USA     Male  55000.0      5.0
2       2    Jane Smith   NaN  Canada   Female  62000.0      3.0
3       3          Alex   NaN     USA  Unknown  47000.0      7.0
4       4  Maria Garcia  34.0   Spain   Female      NaN      NaN
5       5        Li Wei  27.0   China     Male  51000.0      6.0
6       6           NaN  45.0   India   Female  73000.0      1.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8       8    Rachel Lee  29.0     USA   Female  62000.0      3.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0      8.0
10     10   Emily Davis  31.0     USA      NaN  58000.0      4.0

In [29]:
# apply a fnx to a row or col
df2["tax"] = df2["income"].apply(lambda x : "10%" if x < 60000 else "20%")
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA    NaN  55000.0  10%
1    1      John Doe  29.0     USA    NaN  55000.0  10%
2    2    Jane Smith   NaN  Canada    NaN  62000.0  20%
3    3          Alex   NaN     USA    NaN  47000.0  10%
4    4  Maria Garcia  34.0   Spain    NaN      NaN  20%
5    5        Li Wei  27.0   China    NaN  51000.0  10%
6    6           NaN  45.0   India    NaN  73000.0  20%
7    7    Ahmed Khan  38.0     NaN    NaN  68000.0  20%
8    8    Rachel Lee  29.0     USA    NaN  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico    NaN  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [33]:
# map values to another
df3=df.copy()
new_gender_vals = {"Male": "M", "Female": "F", "Unknown": "U"}
df3["gender"] = df3["gender"].map(new_gender_vals)
df3

    id          name   age country gender   income
0    1      John Doe  29.0     USA      M  55000.0
1    1      John Doe  29.0     USA      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN     USA      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0     USA      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0